apiVersion: v1
kind: Service
metadata:
  name: card-service
  labels:
    app: card-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001 # Exposes the service on this port
  selector:
    app: card-service