apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
  labels:
    app: wallet-service
spec:
  replicas: 1  # Single pod with two containers
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
      - name: grpc-server
        image: wallet_service:latest
        imagePullPolicy: Never
        command: ["python", "wallet_server.py"]  # Run the gRPC server
        ports:
        - containerPort: 50051  # gRPC server port
        env:

      - name: http-adapter
        image: wallet_service:latest 
        imagePullPolicy: Never  # Use the same Docker image
        command: ["python", "http_adapter.py"]  # Run the HTTP adapter
        ports:
        - containerPort: 5002  # HTTP adapter port
        env:
        - name: PYTHONUNBUFFERED
          value: "1"