apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  labels:
    app: wallet-service
spec:
  type: NodePort  # Use NodePort for Minikube to expose the service
  ports:
  - port: 5002
    targetPort: 5002
    nodePort: 30002  # Optional: Specify a fixed NodePort
  selector:
    app: wallet-service