# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wallet.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'wallet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cwallet.proto\x12\x06wallet\"5\n\rWalletRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63\x61rd_number\x18\x02 \x01(\t\"3\n\x0eWalletResponse\x12\x11\n\twallet_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x19\n\x0bTestRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x1f\n\x0cTestResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2N\n\rWalletService\x12=\n\x0c\x43reateWallet\x12\x15.wallet.WalletRequest\x1a\x16.wallet.WalletResponse2@\n\x0bTestService\x12\x31\n\x04test\x12\x13.wallet.TestRequest\x1a\x14.wallet.TestResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wallet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WALLETREQUEST']._serialized_start=24
  _globals['_WALLETREQUEST']._serialized_end=77
  _globals['_WALLETRESPONSE']._serialized_start=79
  _globals['_WALLETRESPONSE']._serialized_end=130
  _globals['_TESTREQUEST']._serialized_start=132
  _globals['_TESTREQUEST']._serialized_end=157
  _globals['_TESTRESPONSE']._serialized_start=159
  _globals['_TESTRESPONSE']._serialized_end=190
  _globals['_WALLETSERVICE']._serialized_start=192
  _globals['_WALLETSERVICE']._serialized_end=270
  _globals['_TESTSERVICE']._serialized_start=272
  _globals['_TESTSERVICE']._serialized_end=336
# @@protoc_insertion_point(module_scope)
